name: Flutter CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'kendrix-mobile-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'kendrix-mobile-app/**'

defaults:
  run:
    working-directory: kendrix-mobile-app

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Analyze code
        run: flutter analyze

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./kendrix-mobile-app/coverage/lcov.info
          flags: flutter
          name: kendrix-mobile-app

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build Android APK
        run: flutter build apk -t lib/main_prod.dart --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL || 'https://api.kendrix.com' }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: kendrix-mobile-app/build/app/outputs/flutter-apk/app-release.apk

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build Web
        run: flutter build web -t lib/main_prod.dart --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL || 'https://api.kendrix.com' }}

      - name: Upload Web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: kendrix-mobile-app/build/web/

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: flutter gen-l10n

      - name: Build iOS (no codesign)
        run: flutter build ios -t lib/main_prod.dart --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL || 'https://api.kendrix.com' }} --no-codesign

      - name: Upload iOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: kendrix-mobile-app/build/ios/iphoneos/

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency audit
        run: flutter pub deps --json > deps.json && dart pub global activate pana && pana --no-warning --json . > pana.json || true

      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        with:
          name: security-scan
          path: |
            kendrix-mobile-app/deps.json
            kendrix-mobile-app/pana.json